---
- hosts: all
  vars:
        ansible_ssh_user: 'remote_user'
        ansible_port: 'remote_port'
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_location
        #ansible_sudo_pass: 'Your fucking local password' #enable please if your ansible.cfg there is a configuration `become = yes`
        mountpoint: "/"  #mountpoint disk want to check
        limit_minimum: "90"
  tasks:
   - name: Checking Disk on your Server
     shell: df -h "{{mountpoint}}" | tail -n 1 | awk {'print $5 '}  | sed 's/%//g'
     register: disk

   - name: Create file log and Remove file log if an exist
     shell : rm -rf disk_usage.txt; touch disk_usage.txt
     delegate_to: localhost

   - name: Server List
     shell: echo "{{ inventory_hostname }}"
     register: server

   - name: Show debugging on your fucking terminal
     debug:
       msg:
         - "{{ disk.stdout }}"
         - "{{ server.stdout }}"

   - name: Adding record disk usage to list on file  
     lineinfile:
       dest: disk_usage.txt
       line: "{{ mountpoint }} HAS REACHED {{ disk.stdout }} % ON {{ server.stdout }}, PLEASE CHECK !!!"
       state: present
     delegate_to: 127.0.0.1
     register: msgtxt
     with_items:
       - "{{ disk.stdout }}"
       - "{{ server.stdout }}"
     when: disk.stdout >= limit_minimum #minimum disk usage want add to list
